CREATE TABLE IF NOT EXISTS sms (
  hash TEXT PRIMARY KEY,
  data TEXT NOT NULL,
  sent BOOLEAN NOT NULL DEFAULT FALSE,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  message TEXT NOT NULL,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);
